---
platform: emscripten 
generator: Ninja
build_tool: vscode_cmake 
build_type: Debug
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_EMSCRIPTEN_USE_WASM: ON
    FIPS_EMSCRIPTEN_USE_WASI: ON
    FIPS_EMSCRIPTEN_ALLOW_MEMORY_GROWTH: OFF

